blank_issues_enabled: false
contact_links:
  - name: Translate Neo Launcher
    url: https://hosted.weblate.org/engage/neolauncher/
    about: Help translate Neo Launcher on Weblate
  - name: Matrix Community
    url: https://matrix.to/#/#neo-launcher:matrix.org
    about: 'Join our Matrix community group!'
  - name: Telegram Community
    url: https://t.me/neo_launcher
    about: 'Join our Telegram community group!'
  - name: Discussions
    url: https://github.com/NeoApplications/Neo-Launcher/discussions
    about: View discussions or start one yourself. But be aware that our Telegram & Matrix groups are the preferred way for discussions.
